# Generated by Django 3.2.15 on 2022-09-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('descriptionar', models.CharField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fromdate', models.DateTimeField(auto_now_add=True)),
                ('todate', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencyapp.currency')),
            ],
            options={
                'verbose_name_plural': 'Publicities',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('namear', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('descriptionar', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePublicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('namear', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('descriptionar', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Type Publicities',
            },
        ),
        migrations.CreateModel(
            name='PublicityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('publicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Publicity.publicity')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Publicity.service')),
            ],
        ),
        migrations.AddField(
            model_name='publicity',
            name='service',
            field=models.ManyToManyField(through='Publicity.PublicityService', to='Publicity.Service'),
        ),
        migrations.AddField(
            model_name='publicity',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Address.street'),
        ),
        migrations.AddField(
            model_name='publicity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Publicity.typepublicity'),
        ),
        migrations.AddField(
            model_name='publicity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImagePublicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('publicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Publicity.publicity')),
            ],
            options={
                'verbose_name_plural': 'Images Publicities',
            },
        ),
    ]
