# Generated by Django 3.2.15 on 2022-08-20 05:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=300)),
                ('fromdate', models.DateField(default=datetime.datetime.now)),
                ('todate', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('descriptionar', models.CharField(blank=True, default='', max_length=250)),
                ('todateextended', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comissionguid', models.FloatField(default=0)),
                ('comissionadmin', models.FloatField(default=0)),
                ('fromtimehour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='08', max_length=2)),
                ('fromtimeminute', models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2)),
                ('totimehour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='08', max_length=2)),
                ('totimeminute', models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2)),
                ('totimeextendedhour', models.CharField(blank=True, choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='', max_length=2)),
                ('totimeextendedminute', models.CharField(blank=True, choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='', max_length=2)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Operation.operation')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('namear', models.CharField(default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('descriptionar', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Auction Status',
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biddatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('win', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auction.auction')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auction.auctionstatus'),
        ),
        migrations.AddField(
            model_name='auction',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Address.street'),
        ),
    ]
