# Generated by Django 3.2.15 on 2022-08-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Auction.auction'),
        ),
    ]
