# Generated by Django 3.2.15 on 2022-08-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operation', '0002_auto_20220831_1044'),
        ('Auction', '0002_alter_bids_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='operation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Operation.operation'),
        ),
    ]
