# Generated by Django 3.2.15 on 2022-08-31 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
        ('Operation', '0002_auto_20220831_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Animal.animal'),
        ),
    ]
