# Generated by Django 3.2.15 on 2022-08-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
    ]
