# Generated by Django 3.2.15 on 2022-08-12 14:06

from django.db import migrations
from datetime import datetime

def combine_names(apps, schema_editor):
    # We can't import the Currency model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Currency = apps.get_model('currencyapp', 'Currency')


    currency = Currency.objects.filter(symbol='USD')
    if not currency.exists():
        Currency.objects.create(name='Dollar',namear='دولار',
                                symbol='USD',
                                created_at=datetime.today(),
                                updated_at=datetime.today()
                                )
    currency = Currency.objects.filter(symbol='EUR')
    if not currency.exists():
        Currency.objects.create(name='Euro',namear='يورو',
                                symbol='EUR',
                                created_at=datetime.today(),
                                updated_at=datetime.today()
                                )
    currency = Currency.objects.filter(symbol='SAR')
    if not currency.exists():
        Currency.objects.create(name='Saudi riyal',namear='ريال سعودي',
                                symbol='SAR',
                                created_at=datetime.today(),
                                updated_at=datetime.today()
                                )

    currency = Currency.objects.filter(symbol='AED')
    if not currency.exists():
        Currency.objects.create(name='United Arab Emirates Dirhaml', namear='درهم اماراتي',
                                symbol='AED',
                                created_at=datetime.today(),
                                updated_at=datetime.today()
                                )

class Migration(migrations.Migration):

    dependencies = [
        ('currencyapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
