# Generated by Django 3.2.15 on 2022-08-25 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Complains', '0003_auto_20220825_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomplains',
            name='imageText',
        ),
        migrations.AddField(
            model_name='imagecomplains',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
