# Generated by Django 3.2.15 on 2022-08-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Complains', '0004_auto_20220825_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomplains',
            name='complains',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complains.complains'),
        ),
    ]
